/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_aschuetz_ivshmem4j_windows_WindowsSharedMemory */

#ifndef _Included_de_aschuetz_ivshmem4j_windows_WindowsSharedMemory
#define _Included_de_aschuetz_ivshmem4j_windows_WindowsSharedMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_aschuetz_ivshmem4j_windows_WindowsSharedMemory
 * Method:    getDevices
 * Signature: ()[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_de_aschuetz_ivshmem4j_windows_WindowsSharedMemory_getDevices
  (JNIEnv *, jclass);

/*
 * Class:     de_aschuetz_ivshmem4j_windows_WindowsSharedMemory
 * Method:    openDevice
 * Signature: ([B[J)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_windows_WindowsSharedMemory_openDevice
  (JNIEnv *, jclass, jbyteArray, jlongArray);

/*
 * Class:     de_aschuetz_ivshmem4j_windows_WindowsSharedMemory
 * Method:    close
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_windows_WindowsSharedMemory_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_aschuetz_ivshmem4j_windows_WindowsSharedMemory
 * Method:    sendInterrupt
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_windows_WindowsSharedMemory_sendInterrupt
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     de_aschuetz_ivshmem4j_windows_WindowsSharedMemory
 * Method:    pollInterrupt
 * Signature: (J[I)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_windows_WindowsSharedMemory_pollInterrupt
  (JNIEnv *, jclass, jlong, jintArray);

#ifdef __cplusplus
}
#endif
#endif
