/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_aschuetz_ivshmem4j_linux_plain_LinuxSharedMemory */

#ifndef _Included_de_aschuetz_ivshmem4j_linux_plain_LinuxSharedMemory
#define _Included_de_aschuetz_ivshmem4j_linux_plain_LinuxSharedMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_aschuetz_ivshmem4j_linux_plain_LinuxSharedMemory
 * Method:    createOrOpenFile
 * Signature: (Ljava/lang/String;J[J)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_linux_plain_LinuxSharedMemory_createOrOpenFile
  (JNIEnv *, jclass, jstring, jlong, jlongArray);

/*
 * Class:     de_aschuetz_ivshmem4j_linux_plain_LinuxSharedMemory
 * Method:    close
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_linux_plain_LinuxSharedMemory_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
