/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_aschuetz_ivshmem4j_common_CommonSharedMemory */

#ifndef _Included_de_aschuetz_ivshmem4j_common_CommonSharedMemory
#define _Included_de_aschuetz_ivshmem4j_common_CommonSharedMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    getNativeLibVersion
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_getNativeLibVersion
  (JNIEnv *, jclass);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    write
 * Signature: (JJ[BII)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_write__JJ_3BII
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    write
 * Signature: (JJB)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_write__JJB
  (JNIEnv *, jclass, jlong, jlong, jbyte);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    write
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_write__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    write
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_write__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    write
 * Signature: (JJF)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_write__JJF
  (JNIEnv *, jclass, jlong, jlong, jfloat);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    write
 * Signature: (JJD)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_write__JJD
  (JNIEnv *, jclass, jlong, jlong, jdouble);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    write
 * Signature: (JJS)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_write__JJS
  (JNIEnv *, jclass, jlong, jlong, jshort);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    read
 * Signature: (JJ[BII)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_read__JJ_3BII
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    read
 * Signature: (JJ[I)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_read__JJ_3I
  (JNIEnv *, jclass, jlong, jlong, jintArray);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    read
 * Signature: (JJ[J)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_read__JJ_3J
  (JNIEnv *, jclass, jlong, jlong, jlongArray);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    read
 * Signature: (JJ[F)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_read__JJ_3F
  (JNIEnv *, jclass, jlong, jlong, jfloatArray);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    read
 * Signature: (JJ[D)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_read__JJ_3D
  (JNIEnv *, jclass, jlong, jlong, jdoubleArray);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    read
 * Signature: (JJ[S)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_read__JJ_3S
  (JNIEnv *, jclass, jlong, jlong, jshortArray);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    read
 * Signature: (JJ[B)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_read__JJ_3B
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    memset
 * Signature: (JJBJ)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_memset
  (JNIEnv *, jclass, jlong, jlong, jbyte, jlong);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    xadd
 * Signature: (JJ[J)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_xadd__JJ_3J
  (JNIEnv *, jclass, jlong, jlong, jlongArray);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    xadd
 * Signature: (JJ[I)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_xadd__JJ_3I
  (JNIEnv *, jclass, jlong, jlong, jintArray);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    xadd
 * Signature: (JJ[S)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_xadd__JJ_3S
  (JNIEnv *, jclass, jlong, jlong, jshortArray);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    xadd
 * Signature: (JJ[B)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_xadd__JJ_3B
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    xchg
 * Signature: (JJ[J)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_xchg__JJ_3J
  (JNIEnv *, jclass, jlong, jlong, jlongArray);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    xchg
 * Signature: (JJ[I)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_xchg__JJ_3I
  (JNIEnv *, jclass, jlong, jlong, jintArray);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    xchg
 * Signature: (JJ[S)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_xchg__JJ_3S
  (JNIEnv *, jclass, jlong, jlong, jshortArray);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    xchg
 * Signature: (JJ[B)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_xchg__JJ_3B
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    cmpxchg
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_cmpxchg__JJJJ
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    cmpxchg
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_cmpxchg__JJII
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    cmpxchg
 * Signature: (JJSS)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_cmpxchg__JJSS
  (JNIEnv *, jclass, jlong, jlong, jshort, jshort);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    cmpxchg
 * Signature: (JJBB)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_cmpxchg__JJBB
  (JNIEnv *, jclass, jlong, jlong, jbyte, jbyte);

/*
 * Class:     de_aschuetz_ivshmem4j_common_CommonSharedMemory
 * Method:    cmpxchg16b
 * Signature: (JJ[B)J
 */
JNIEXPORT jlong JNICALL Java_de_aschuetz_ivshmem4j_common_CommonSharedMemory_cmpxchg16b
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
